### ISSUE TITLE
Missing latest versions in repo

### ISSUE THREAD

**Issue by PikaMug** [MagmaGuy/EasyMinecraftGoals#2]
See https://github.com/MagmaGuy/EliteMobs/issues/167

**Comment by MagmaGuy** [comment]
My bad, I moved all my repos but it was in the middle of doing so many things I have no yet documented it fully.

The new repo for all of my plugins is located at 

https://repo.magmaguy.com/

In this instance, you're looking for 

```
<repository>
  <id>magmaguy-repo-releases</id>
  <name>MagmaGuy's Repository</name>
  <url>https://repo.magmaguy.com/releases</url>
</repository>

<dependency>
  <groupId>com.magmaguy</groupId>
  <artifactId>EasyMinecraftGoals-dist</artifactId>
  <version>1.13.0</version>
</dependency>
```
